### ISSUE TITLE
php

### ISSUE THREAD

**Issue by mellbo** [vrachieru/eon-api#2]
ceva in pentru php ai lucrat?

**Comment by vrachieru** [comment]
Nu. Dar nu ar fi greu sa replici request-urile catre API-ul lor in ce  limbaj vrei tu.

**Comment by mellbo** [comment]
știu dar ma gândeam că scap mai ieftin 😊

vin., 8 ian. 2021, 23:44 Victor Rachieru <notifications@github.com> a scris:
